threadtree/gevent: bug fix for python3.11 around getting all greenlets
  */easypy/concurrency.py:483 ......................... dump_stacks >> frames = dict(iter_thread_frames())
  */easypy/threadtree.py:138 ................... iter_thread_frames >> all_greenlets = get_all_greenlets()
  */easypy/threadtree.py:120 .................... get_all_greenlets >> return {g for g in gc.get_objects() if isinstance(g, Greenlet)}
  */easypy/threadtree.py:120 ............................ <setcomp> >> return {g for g in gc.get_objects() if isinstance(g, Greenlet)}
ReferenceError: weakly-referenced object no longer exists